sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
services:
  - mongodb
before_script:
  - sleep 15
  - mongo dstore_test --eval 'db.createUser({user: "test", pwd: "test123", roles: [{ role: "readWrite", db: "dstore_test" }]});'
install:
  - pip install -q -r dev_requirements.txt
  - pip install coveralls
script:
  - nosetests -vs tests --with-coverage --cover-package=dstore
after_success:
  - coveralls
